### PR TITLE
filter by key openmp guard

### LINKED ISSUE #157: Guard openmp code in filter-by-key app

### PR DESCRIPTION
**Pull request by fasiddique**
Closes #157

### CODE REVIEW

**Review by deyuan — CHANGES_REQUESTED** [review]
This application has below code in db-filtering.cpp which requires special handling:
        int tid = omp_get_thread_num();
@fzx333 mentioned this is no longer needed. We need to clean up both to pass compilation without OpenMP.

**Comment by fasiddique** [comment]
> This application has below code in db-filtering.cpp which requires special handling: int tid = omp_get_thread_num(); @fzx333 mentioned this is no longer needed. We need to clean up both to pass compilation without OpenMP.

@deyuan  I can see that this is used to divide task among the threads. @fzx333, will you please confirm?

**Review by fzx333 — APPROVED** [review]

**Comment by fzx333** [comment]
We can just add the openMP guard for now for the purpose of cleanness, and the code will also work. In terms of the changes I mentioned, it might involve more code changes, and I will do them in a future PR.

**Review by deyuan — APPROVED** [review]
The changes are good but not complete. Without handling omp_get_thread_num(), the app cannot be compiled without OpenMP library. I'm okay to merge this and let @fzx333 update the code separately.

**Pull request merged**
